### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by j-nord** [RamdhasUeikattan/ChildCompDataBind#1]
No data in the grid: No records to display

**Comment by RamdhasUeikattan** [comment]
Initially, Grid renders with empty. You can search the customer detail using the search box.

For example: If you type 'VINET' and search, The matching details were got from service and it showed on the grid.

**Comment by RamdhasUeikattan** [comment]
Now, we changed the sample to your requirement that is given from that conversation. please refer that sample. Now grid renders on initial and you can change the grid data source and column schema using the dropdown.
